[2021-02-05 11:18:19,471] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs 2021-01-12T00:00:00+00:00 [queued]>
[2021-02-05 11:18:19,479] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs 2021-01-12T00:00:00+00:00 [queued]>
[2021-02-05 11:18:19,480] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 11:18:19,480] {taskinstance.py:881} INFO - Starting attempt 1 of 4
[2021-02-05 11:18:19,480] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 11:18:19,483] {taskinstance.py:901} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2021-01-12T00:00:00+00:00
[2021-02-05 11:18:19,488] {standard_task_runner.py:54} INFO - Started process 29143 to run task
[2021-02-05 11:18:19,519] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Stage_songs', '2021-01-12T00:00:00+00:00', '--job_id', '1027', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmp7c3u9pvg']
[2021-02-05 11:18:19,520] {standard_task_runner.py:78} INFO - Job 1027: Subtask Stage_songs
[2021-02-05 11:18:19,538] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Stage_songs 2021-01-12T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-05 11:18:19,596] {stage_redshift.py:57} INFO - Clearing data from destination Redshift table: staging_songs
[2021-02-05 11:18:19,599] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-05 11:18:20,922] {dbapi_hook.py:176} INFO - DELETE FROM staging_songs
[2021-02-05 11:19:54,699] {local_task_job.py:143} WARNING - The recorded hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa does not match this instance's hostname trevors-macbook-air.local
[2021-02-05 11:19:54,712] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 29143
[2021-02-05 11:20:00,100] {taskinstance.py:955} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-05 11:20:00,110] {taskinstance.py:1150} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/trevorransom/Documents/01 Coding/03 Data Engineering/Udacity/05 Airflow/plugins/operators/stage_redshift.py", line 58, in execute
    redshift.run('DELETE FROM {}'.format(self.table))
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 957, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-02-05 11:20:00,113] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_songs, execution_date=20210112T000000, start_date=20210205T091819, end_date=20210205T092000
[2021-02-05 11:20:00,155] {helpers.py:291} INFO - Process psutil.Process(pid=29143, status='terminated', exitcode=1, started='11:18:19') (29143) terminated with exit code 1
