[2021-02-04 17:16:47,213] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2021-02-04T15:11:25.377363+00:00 [queued]>
[2021-02-04 17:16:47,223] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2021-02-04T15:11:25.377363+00:00 [queued]>
[2021-02-04 17:16:47,223] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 17:16:47,223] {taskinstance.py:881} INFO - Starting attempt 2 of 4
[2021-02-04 17:16:47,223] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 17:16:47,228] {taskinstance.py:901} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2021-02-04T15:11:25.377363+00:00
[2021-02-04 17:16:47,233] {standard_task_runner.py:54} INFO - Started process 44296 to run task
[2021-02-04 17:16:47,270] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Stage_events', '2021-02-04T15:11:25.377363+00:00', '--job_id', '724', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmpwlbt_13q']
[2021-02-04 17:16:47,273] {standard_task_runner.py:78} INFO - Job 724: Subtask Stage_events
[2021-02-04 17:16:47,291] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Stage_events 2021-02-04T15:11:25.377363+00:00 [running]> on host Trevors-MacBook-Air.local
[2021-02-04 17:16:47,381] {stage_redshift.py:57} INFO - Clearing data from destination Redshift table: staging_events
[2021-02-04 17:16:47,385] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-04 17:16:48,757] {dbapi_hook.py:176} INFO - DELETE FROM staging_events
[2021-02-04 17:16:49,388] {stage_redshift.py:60} INFO - Copying data from S3 to Redshift
[2021-02-04 17:16:49,403] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-04 17:16:50,718] {dbapi_hook.py:176} INFO - 
        COPY staging_events
        FROM 's3://udacity-dend/log_data'
        ACCESS_KEY_ID 'AKIA2IMWSL5GKAQJ27TS'
        SECRET_ACCESS_KEY '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'
        IGNOREHEADER 1
        DELIMITER ','
    
[2021-02-04 17:16:51,419] {taskinstance.py:1150} ERROR - Load into table 'staging_events' failed.  Check 'stl_load_errors' system table for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/trevorransom/Documents/01 Coding/03 Data Engineering/Udacity/05 Airflow/plugins/operators/stage_redshift.py", line 71, in execute
    redshift.run(formatted_sql)
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.InternalError_: Load into table 'staging_events' failed.  Check 'stl_load_errors' system table for details.

[2021-02-04 17:16:51,430] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_events, execution_date=20210204T151125, start_date=20210204T151647, end_date=20210204T151651
[2021-02-04 17:16:52,229] {local_task_job.py:102} INFO - Task exited with return code 1
