[2021-02-04 14:29:36,961] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2019-01-12T02:00:00+00:00 [queued]>
[2021-02-04 14:29:36,969] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2019-01-12T02:00:00+00:00 [queued]>
[2021-02-04 14:29:36,969] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 14:29:36,969] {taskinstance.py:881} INFO - Starting attempt 6 of 7
[2021-02-04 14:29:36,969] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 14:29:36,974] {taskinstance.py:901} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-01-12T02:00:00+00:00
[2021-02-04 14:29:36,979] {standard_task_runner.py:54} INFO - Started process 59533 to run task
[2021-02-04 14:29:37,025] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Stage_events', '2019-01-12T02:00:00+00:00', '--job_id', '184', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmpne7egwny']
[2021-02-04 14:29:37,032] {standard_task_runner.py:78} INFO - Job 184: Subtask Stage_events
[2021-02-04 14:29:37,070] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Stage_events 2019-01-12T02:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-04 14:29:37,084] {stage_redshift.py:56} INFO - StageToRedshiftOperator not implemented yet
[2021-02-04 14:29:37,149] {stage_redshift.py:61} INFO - Clearing data from destination Redshift table: staging_events
[2021-02-04 14:29:37,152] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-04 14:29:38,930] {dbapi_hook.py:176} INFO - DELETE FROM staging_events
[2021-02-04 14:29:39,300] {taskinstance.py:1150} ERROR - relation "staging_events" does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/trevorransom/Documents/01 Coding/03 Data Engineering/Udacity/05 Airflow/plugins/operators/stage_redshift.py", line 62, in execute
    redshift.run('DELETE FROM {}'.format(self.table))
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.UndefinedTable: relation "staging_events" does not exist

[2021-02-04 14:29:39,306] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_events, execution_date=20190112T020000, start_date=20210204T122936, end_date=20210204T122939
[2021-02-04 14:29:41,978] {local_task_job.py:102} INFO - Task exited with return code 1
