[2021-02-04 17:17:24,566] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2021-02-04T14:07:34.494859+00:00 [queued]>
[2021-02-04 17:17:24,574] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2021-02-04T14:07:34.494859+00:00 [queued]>
[2021-02-04 17:17:24,574] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 17:17:24,574] {taskinstance.py:881} INFO - Starting attempt 2 of 4
[2021-02-04 17:17:24,574] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 17:17:24,577] {taskinstance.py:901} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2021-02-04T14:07:34.494859+00:00
[2021-02-04 17:17:24,583] {standard_task_runner.py:54} INFO - Started process 44740 to run task
[2021-02-04 17:17:24,617] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Stage_events', '2021-02-04T14:07:34.494859+00:00', '--job_id', '727', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmp2ith4cip']
[2021-02-04 17:17:24,619] {standard_task_runner.py:78} INFO - Job 727: Subtask Stage_events
[2021-02-04 17:17:24,637] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Stage_events 2021-02-04T14:07:34.494859+00:00 [running]> on host Trevors-MacBook-Air.local
[2021-02-04 17:17:24,697] {stage_redshift.py:57} INFO - Clearing data from destination Redshift table: staging_events
[2021-02-04 17:17:24,699] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-04 17:17:26,014] {dbapi_hook.py:176} INFO - DELETE FROM staging_events
[2021-02-04 17:17:26,633] {stage_redshift.py:60} INFO - Copying data from S3 to Redshift
[2021-02-04 17:17:26,644] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-04 17:17:27,951] {dbapi_hook.py:176} INFO - 
        COPY staging_events
        FROM 's3://udacity-dend/log_data'
        ACCESS_KEY_ID 'AKIA2IMWSL5GKAQJ27TS'
        SECRET_ACCESS_KEY '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'
        IGNOREHEADER 1
        DELIMITER ','
    
[2021-02-04 17:17:28,532] {taskinstance.py:1150} ERROR - Load into table 'staging_events' failed.  Check 'stl_load_errors' system table for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/trevorransom/Documents/01 Coding/03 Data Engineering/Udacity/05 Airflow/plugins/operators/stage_redshift.py", line 71, in execute
    redshift.run(formatted_sql)
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.InternalError_: Load into table 'staging_events' failed.  Check 'stl_load_errors' system table for details.

[2021-02-04 17:17:28,539] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_events, execution_date=20210204T140734, start_date=20210204T151724, end_date=20210204T151728
[2021-02-04 17:17:29,564] {local_task_job.py:102} INFO - Task exited with return code 1
