[2021-02-04 14:24:40,348] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2019-01-12T03:00:00+00:00 [queued]>
[2021-02-04 14:24:40,354] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2019-01-12T03:00:00+00:00 [queued]>
[2021-02-04 14:24:40,354] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 14:24:40,354] {taskinstance.py:881} INFO - Starting attempt 5 of 7
[2021-02-04 14:24:40,354] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 14:24:40,357] {taskinstance.py:901} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-01-12T03:00:00+00:00
[2021-02-04 14:24:40,363] {standard_task_runner.py:54} INFO - Started process 56016 to run task
[2021-02-04 14:24:40,400] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Stage_events', '2019-01-12T03:00:00+00:00', '--job_id', '165', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmp1xuilani']
[2021-02-04 14:24:40,401] {standard_task_runner.py:78} INFO - Job 165: Subtask Stage_events
[2021-02-04 14:24:40,423] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Stage_events 2019-01-12T03:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-04 14:24:40,438] {stage_redshift.py:56} INFO - StageToRedshiftOperator not implemented yet
[2021-02-04 14:24:40,494] {stage_redshift.py:61} INFO - Clearing data from destination Redshift table: staging_events
[2021-02-04 14:24:40,498] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-04 14:24:41,818] {dbapi_hook.py:176} INFO - DELETE FROM staging_events
[2021-02-04 14:24:42,190] {taskinstance.py:1150} ERROR - relation "staging_events" does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/trevorransom/Documents/01 Coding/03 Data Engineering/Udacity/05 Airflow/plugins/operators/stage_redshift.py", line 62, in execute
    redshift.run('DELETE FROM {}'.format(self.table))
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.UndefinedTable: relation "staging_events" does not exist

[2021-02-04 14:24:42,191] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_events, execution_date=20190112T030000, start_date=20210204T122440, end_date=20210204T122442
[2021-02-04 14:24:45,357] {local_task_job.py:102} INFO - Task exited with return code 1
